spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pl_payment_v1
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 10000

  kafka:
    bootstrap-servers: localhost:10000,localhost:10001,localhost:10002

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

payment:
  toss:
    success_url: ${TOSS_PAYMENT_SUCCESS_URL_DEV}
    fail_url: ${TOSS_PAYMENT_FAIL_URL_DEV}