server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true

springdoc:
  api-docs:
    path: /v3/api-docs

spring:
  application:
    name: payment-service
  profiles:
    active: prod

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  kafka:
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
    topics:
      payment-created: payment-created

payment:
  toss:
    client_key: ${TOSS_PAYMENT_CLIENT_KEY}
    secret_key: ${TOSS_PAYMENT_SECRET_KEY}
    base_url: ${TOSS_PAYMENT_BASE_URL}
    success_url: ${TOSS_PAYMENT_SUCCESS_URL}
    fail_url: ${TOSS_PAYMENT_FAIL_URL}

logging:
  level:
    root: INFO